[[ginkgo]]
arch = "aarch64"
git-tree-sha1 = "58c8f650665085e42f353de7000f981f4a03216c"
libc = "glibc"
os = "linux"

    [[ginkgo.download]]
    sha256 = "649adcdb3e4e79c8eab78728b88e26ec2932a513862be9e4c3178cf6796e9259"
    url = "https://github.com/youwuyou/ginkgo_jll.jl/releases/download/ginkgo-v1.6.2+0/ginkgo.v1.6.2.aarch64-linux-gnu.tar.gz"
[[ginkgo]]
arch = "aarch64"
git-tree-sha1 = "ef326b9cd953d6335e2e6dc4aad9603e27db65cb"
libc = "musl"
os = "linux"

    [[ginkgo.download]]
    sha256 = "9f7fe10b6e362aae6fc95358bf7cdf02935b58c7802b58749544bd9230965978"
    url = "https://github.com/youwuyou/ginkgo_jll.jl/releases/download/ginkgo-v1.6.2+0/ginkgo.v1.6.2.aarch64-linux-musl.tar.gz"
[[ginkgo]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3e1f39251c865281f21b99acbb90d3457f9facdf"
libc = "glibc"
os = "linux"

    [[ginkgo.download]]
    sha256 = "c72541331e4e9b2ac88dd8d41e50d055800cc0a11003f17f540ec8313f883d1d"
    url = "https://github.com/youwuyou/ginkgo_jll.jl/releases/download/ginkgo-v1.6.2+0/ginkgo.v1.6.2.armv6l-linux-gnueabihf.tar.gz"
[[ginkgo]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "dee3fb67dd8f102510192643f130a8b870ac2718"
libc = "musl"
os = "linux"

    [[ginkgo.download]]
    sha256 = "88197ddd0d7ca624cf07ebe7c1e90677a25a2589667fc3ba516cee894ceaa786"
    url = "https://github.com/youwuyou/ginkgo_jll.jl/releases/download/ginkgo-v1.6.2+0/ginkgo.v1.6.2.armv6l-linux-musleabihf.tar.gz"
[[ginkgo]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "83805be89a87861e23ffbab964fa26c77db42ffc"
libc = "glibc"
os = "linux"

    [[ginkgo.download]]
    sha256 = "2f2a3c7d409fcc49800298dd477087dfc80074d50df31abc69c36af77bec86ff"
    url = "https://github.com/youwuyou/ginkgo_jll.jl/releases/download/ginkgo-v1.6.2+0/ginkgo.v1.6.2.armv7l-linux-gnueabihf.tar.gz"
[[ginkgo]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "402a09738a09be9fb9f4c1e230a012c5c950e619"
libc = "musl"
os = "linux"

    [[ginkgo.download]]
    sha256 = "12e0775dd20dedba9bf866e02560e2e3b0d3c76202a605c6a9b217d5860793ec"
    url = "https://github.com/youwuyou/ginkgo_jll.jl/releases/download/ginkgo-v1.6.2+0/ginkgo.v1.6.2.armv7l-linux-musleabihf.tar.gz"
[[ginkgo]]
arch = "i686"
git-tree-sha1 = "95e80ac94dbcfd2f587c0c709c8ff3b89f370811"
libc = "glibc"
os = "linux"

    [[ginkgo.download]]
    sha256 = "27e77d0b80c85886340419f7339a11628f5df56981bd943285cef397393b770a"
    url = "https://github.com/youwuyou/ginkgo_jll.jl/releases/download/ginkgo-v1.6.2+0/ginkgo.v1.6.2.i686-linux-gnu.tar.gz"
[[ginkgo]]
arch = "i686"
git-tree-sha1 = "74bf436a834352607714d2721970469abefde129"
libc = "musl"
os = "linux"

    [[ginkgo.download]]
    sha256 = "959fbe93693c381c573dca6c5fb1a300a41e9268ce9141a3f599f5bc49892361"
    url = "https://github.com/youwuyou/ginkgo_jll.jl/releases/download/ginkgo-v1.6.2+0/ginkgo.v1.6.2.i686-linux-musl.tar.gz"
[[ginkgo]]
arch = "powerpc64le"
git-tree-sha1 = "0bfc726c412412e05951fca3ab82ae191773cd51"
libc = "glibc"
os = "linux"

    [[ginkgo.download]]
    sha256 = "a2d52e136a5249d4939d6f10b26c18b61b453910f45a232eba5eb222f8076ee5"
    url = "https://github.com/youwuyou/ginkgo_jll.jl/releases/download/ginkgo-v1.6.2+0/ginkgo.v1.6.2.powerpc64le-linux-gnu.tar.gz"
[[ginkgo]]
arch = "x86_64"
git-tree-sha1 = "6b61d3ec64773531225171d7d26b9e6ec06baf92"
libc = "glibc"
os = "linux"

    [[ginkgo.download]]
    sha256 = "d986cb605d2110efb19f0c992adc0d3539ad392e85067e972e92330e8c8f72bc"
    url = "https://github.com/youwuyou/ginkgo_jll.jl/releases/download/ginkgo-v1.6.2+0/ginkgo.v1.6.2.x86_64-linux-gnu.tar.gz"
[[ginkgo]]
arch = "x86_64"
git-tree-sha1 = "ea8fc0c6a0f975dddc561ff4fc09d5ded2efc512"
libc = "musl"
os = "linux"

    [[ginkgo.download]]
    sha256 = "0087805942f7cf3cc019fc267b033f2fb99eb138b2618d8a0a51e73de0c65bc4"
    url = "https://github.com/youwuyou/ginkgo_jll.jl/releases/download/ginkgo-v1.6.2+0/ginkgo.v1.6.2.x86_64-linux-musl.tar.gz"
[[ginkgo]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "39ab98e011f9550d20996a7e0036efebcde3e0dc"
libc = "glibc"
os = "linux"

    [[ginkgo.download]]
    sha256 = "d78e6a7f2905e7cf6ff955134a086a192606bcd2f21008012e390a523e6cef5f"
    url = "https://github.com/youwuyou/ginkgo_jll.jl/releases/download/ginkgo-v1.6.5+0/ginkgo.v1.6.5.aarch64-linux-gnu-cxx03.tar.gz"
[[ginkgo]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ca54afcb4279c95d1b5dbcf9cfdc0870453a370a"
libc = "glibc"
os = "linux"

    [[ginkgo.download]]
    sha256 = "d6522a3851feb4b2f55d63ca7dcbbd823651a690f0dda7d04a116a398ca1045e"
    url = "https://github.com/youwuyou/ginkgo_jll.jl/releases/download/ginkgo-v1.6.5+0/ginkgo.v1.6.5.aarch64-linux-gnu-cxx11.tar.gz"
[[ginkgo]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "be5aa41edf620d011a746ef4de388396831c6f3a"
libc = "musl"
os = "linux"

    [[ginkgo.download]]
    sha256 = "855ddb3be8ac16c5bfb565be90d8fadff75b5af7206421c89df11ab4fa0bd25d"
    url = "https://github.com/youwuyou/ginkgo_jll.jl/releases/download/ginkgo-v1.6.5+0/ginkgo.v1.6.5.aarch64-linux-musl-cxx03.tar.gz"
[[ginkgo]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e99caa2adeb04c1d9327de7a831fa0181d4d333f"
libc = "musl"
os = "linux"

    [[ginkgo.download]]
    sha256 = "c3c3d14c4371bbefaef9cfd3308f42f303e9aa65e5802500b1f05f50ff336ab4"
    url = "https://github.com/youwuyou/ginkgo_jll.jl/releases/download/ginkgo-v1.6.5+0/ginkgo.v1.6.5.aarch64-linux-musl-cxx11.tar.gz"
[[ginkgo]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2f14c505d27228a561dd29b7021e927ff54d74a1"
libc = "glibc"
os = "linux"

    [[ginkgo.download]]
    sha256 = "4dd9c221a633705206bae002f4c45551e5952482cd9f05dfdc2ca230c2761eb2"
    url = "https://github.com/youwuyou/ginkgo_jll.jl/releases/download/ginkgo-v1.6.5+0/ginkgo.v1.6.5.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[ginkgo]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "baeef1d52c8402691f5494cea1606ead8f6d5e01"
libc = "glibc"
os = "linux"

    [[ginkgo.download]]
    sha256 = "9e0f7e958ae38f379805353ffed311c0b5bdf92ad7eee8a841890f7c3acfe488"
    url = "https://github.com/youwuyou/ginkgo_jll.jl/releases/download/ginkgo-v1.6.5+0/ginkgo.v1.6.5.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[ginkgo]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1cdffa844387cad94d72f43a4f9863b725ac4226"
libc = "musl"
os = "linux"

    [[ginkgo.download]]
    sha256 = "ca3289f1eb13c97278798b62a33e3097b1e9902e7b8b7c3443b5566c42a5a64a"
    url = "https://github.com/youwuyou/ginkgo_jll.jl/releases/download/ginkgo-v1.6.5+0/ginkgo.v1.6.5.armv6l-linux-musleabihf-cxx03.tar.gz"
[[ginkgo]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2bfa6687c2dc3717ae5f9d992d728fa8ac3818f4"
libc = "musl"
os = "linux"

    [[ginkgo.download]]
    sha256 = "88b293bcc2265ea5e109af498caa02dadae301a248103c3158104ba12f395562"
    url = "https://github.com/youwuyou/ginkgo_jll.jl/releases/download/ginkgo-v1.6.5+0/ginkgo.v1.6.5.armv6l-linux-musleabihf-cxx11.tar.gz"
[[ginkgo]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "65a47be81cb91305b7a15e2c11f815409bd0a953"
libc = "glibc"
os = "linux"

    [[ginkgo.download]]
    sha256 = "23f3e27dff0daba42437c1ec3ef7f1a208548ce230c36cac9af75d525b23f4d5"
    url = "https://github.com/youwuyou/ginkgo_jll.jl/releases/download/ginkgo-v1.6.5+0/ginkgo.v1.6.5.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[ginkgo]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3eef28d339c50b778991ff7d4f6b2b9e00dabb2e"
libc = "glibc"
os = "linux"

    [[ginkgo.download]]
    sha256 = "ea80be235dcd88fdf434c50ea2d218af5bd20179d14e7985aff881cce1ea8fc2"
    url = "https://github.com/youwuyou/ginkgo_jll.jl/releases/download/ginkgo-v1.6.5+0/ginkgo.v1.6.5.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[ginkgo]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "43f90be0494d00a74f0a558bbdfc1609feb5c944"
libc = "musl"
os = "linux"

    [[ginkgo.download]]
    sha256 = "d48d1f2fe2fae32d5c6de1ca0bc20a4cefb083c8863f1543bcf71c44d8162e4a"
    url = "https://github.com/youwuyou/ginkgo_jll.jl/releases/download/ginkgo-v1.6.5+0/ginkgo.v1.6.5.armv7l-linux-musleabihf-cxx03.tar.gz"
[[ginkgo]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e96ee826689bf8d9bb97e2e640417516743add35"
libc = "musl"
os = "linux"

    [[ginkgo.download]]
    sha256 = "ce61aa65f4feb4e24a99066654da75e720a74095758918f7260a6fe26a6b8dd4"
    url = "https://github.com/youwuyou/ginkgo_jll.jl/releases/download/ginkgo-v1.6.5+0/ginkgo.v1.6.5.armv7l-linux-musleabihf-cxx11.tar.gz"
[[ginkgo]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c7f35cb881ee66fcd95a860deebf17095b6dc26a"
libc = "glibc"
os = "linux"

    [[ginkgo.download]]
    sha256 = "5e8501e026258a4c19dbb6a2d4e34be28991d11a611990314ff1abddc9a9736c"
    url = "https://github.com/youwuyou/ginkgo_jll.jl/releases/download/ginkgo-v1.6.5+0/ginkgo.v1.6.5.i686-linux-gnu-cxx03.tar.gz"
[[ginkgo]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6eb8472fe57af6bd86fddc162704e30cf095d34d"
libc = "glibc"
os = "linux"

    [[ginkgo.download]]
    sha256 = "6d541c045a8c3898d670b74367e8f7c13504daa85338b3ea986125e66c1cb0d5"
    url = "https://github.com/youwuyou/ginkgo_jll.jl/releases/download/ginkgo-v1.6.5+0/ginkgo.v1.6.5.i686-linux-gnu-cxx11.tar.gz"
[[ginkgo]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dfe5b2e4f789c29405bb74eb78540940eb6ade25"
libc = "musl"
os = "linux"

    [[ginkgo.download]]
    sha256 = "118d8ce072f7f15b46c99c3600ce8ef648c651130b86764ba1408f6bca6df636"
    url = "https://github.com/youwuyou/ginkgo_jll.jl/releases/download/ginkgo-v1.6.5+0/ginkgo.v1.6.5.i686-linux-musl-cxx03.tar.gz"
[[ginkgo]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b900d71c03863216b1d3d71a237639995f3f23cf"
libc = "musl"
os = "linux"

    [[ginkgo.download]]
    sha256 = "e2615e22f9d958bf90c9ed531d18f20367edc178df382deb43dc14ace30185e0"
    url = "https://github.com/youwuyou/ginkgo_jll.jl/releases/download/ginkgo-v1.6.5+0/ginkgo.v1.6.5.i686-linux-musl-cxx11.tar.gz"
[[ginkgo]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "10d34bd5712d5caa670cc30a660cc65a7e5336b0"
libc = "glibc"
os = "linux"

    [[ginkgo.download]]
    sha256 = "66103662c9066c8347999b9bedb3e98ae486273f3e9191b0f6a4b63049b16248"
    url = "https://github.com/youwuyou/ginkgo_jll.jl/releases/download/ginkgo-v1.6.5+0/ginkgo.v1.6.5.powerpc64le-linux-gnu-cxx03.tar.gz"
[[ginkgo]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9f739a9bfccd25bfd4f4d60432d7238d53b650c7"
libc = "glibc"
os = "linux"

    [[ginkgo.download]]
    sha256 = "b1223e4b3bd5cc610bb836b959e2b0ff218f2817be7a32f116cc4e8c1485b778"
    url = "https://github.com/youwuyou/ginkgo_jll.jl/releases/download/ginkgo-v1.6.5+0/ginkgo.v1.6.5.powerpc64le-linux-gnu-cxx11.tar.gz"
[[ginkgo]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4a67c1490b153c149727609e989683331efb3136"
libc = "glibc"
os = "linux"

    [[ginkgo.download]]
    sha256 = "18230702c3b778448aba43484226f237ff456ebf300bf15a5c891c87844d1854"
    url = "https://github.com/youwuyou/ginkgo_jll.jl/releases/download/ginkgo-v1.6.5+0/ginkgo.v1.6.5.x86_64-linux-gnu-cxx03.tar.gz"
[[ginkgo]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5e7e3ec6fb4bb6b4aeb9c6abaea352627e6239c1"
libc = "glibc"
os = "linux"

    [[ginkgo.download]]
    sha256 = "324751818c8fc439054e747e584fedccfb368eaf290ec023bbac109816bce995"
    url = "https://github.com/youwuyou/ginkgo_jll.jl/releases/download/ginkgo-v1.6.5+0/ginkgo.v1.6.5.x86_64-linux-gnu-cxx11.tar.gz"
[[ginkgo]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "872db77d1c0aee4385fbfa5ae768a693a010596f"
libc = "musl"
os = "linux"

    [[ginkgo.download]]
    sha256 = "87250655d67040d623a2304f497efcba706bd2fbdad62a750ac482ae44b98441"
    url = "https://github.com/youwuyou/ginkgo_jll.jl/releases/download/ginkgo-v1.6.5+0/ginkgo.v1.6.5.x86_64-linux-musl-cxx03.tar.gz"
[[ginkgo]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b4bd494c19f0bc0268ab188ed18c53985bab11f0"
libc = "musl"
os = "linux"

    [[ginkgo.download]]
    sha256 = "4ff3fbc76e44347560b4594277249668db44f0765102b9549ff625d9a8892adc"
    url = "https://github.com/youwuyou/ginkgo_jll.jl/releases/download/ginkgo-v1.6.5+0/ginkgo.v1.6.5.x86_64-linux-musl-cxx11.tar.gz"
